services:
  bench_ros2:
    container_name: motion-planning
    image: bench_ros2
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    # ipc: host
    network_mode: host
    environment:
      SDL_VIDEODRIVER: x11
      DISPLAY: $DISPLAY
      ROS_DOMAIN_ID: 34
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/home/ros/ws/src/nav2_mod_planner
      - /dev/bus/usb/:/dev/bus/usb
    stdin_open: true
    privileged: true
    group_add:
      - video
    tty: true
    command: tail -f /dev/null
    restart: always
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [compute,utility,graphics,display]
  
